collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  services:
    path: _services
    name: Services
    icon: devices
    sort:
      key: weight
  team:
    path: _team
    name: Team
    icon: tram
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
paths:
  static: ''
  uploads: uploads
timezone: America/Chicago
markdown:
  engine: kramdown
  options:
    heading_ids: false
    gfm: false
    breaks: false
    typographer: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
    treat_indentation_as_code: true
_snippets_imports:
  jekyll: true
